# Respirometry

```{r load_data_functional}
load("data/data.Rdata")
respirometry_resp2 <- read_excel("respirometry_resp2.xlsx")
```

```{r dataframe_modify}
respirometry_resp2$individual<-as.factor(respirometry_resp2$individual)
respirometry_resp2$cage<-as.factor(respirometry_resp2$cage)
respirometry_resp2$time_point<-as.factor(respirometry_resp2$time_point)
respirometry_resp2$type<-as.factor(respirometry_resp2$type)
respirometry_resp2$population<-as.factor(respirometry_resp2$population)
respirometry_resp2$QC_normalized<-as.numeric(respirometry_resp2$QC_normalized)
respirometry_resp2$r2<-as.numeric(respirometry_resp2$r2)


#Filter NA values
respirometry_resp2<-respirometry_resp2 %>%
  filter(QC_normalized!="NA")
```

#Acclimation oxygen consumption

```{r plot}
respirometry_resp2 %>%
  filter(time_point=="0")%>%
  filter(individual!="AH1_2nd_8")%>%
  ggplot(aes(x = population, y = QC_normalized, color=population, fill=population, alpha=0.2)) +
    geom_boxplot()+
    geom_jitter() +
      scale_color_manual(name="Population",
          breaks=c("Cold","Warm"),
          labels=c("Cold","Warm"),
          values=c('#008080', "#d57d2c")) +
      scale_fill_manual(name="Population",
          breaks=c("Cold","Warm"),
          labels=c("Cold","Warm"),
          values=c('#00808050', "#d57d2c50"))+
    #geom_text(aes(label = individual), hjust = 0, nudge_x = 0.05) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))+
    stat_compare_means(size=3,vjust = 3, hjust=1 )+
    theme(legend.position="none")+
    labs(x = "Population", y= "Normalized O2 consumption (ml/s/g)")
```

# Time-point oxygen consumption

```{r plot_1}
respirometry_resp2 %>%
  filter(weight!=5.19)%>%
  ggplot(aes(x = time_point, y = QC_normalized, color=time_point, fill=time_point, alpha=0.2)) +
    geom_boxplot()+
    geom_jitter() +
      scale_color_manual(name="Time_point",
          breaks=c("0","1","2"),
          labels=c("Acclimation","1 week post FMT", "2 weeks post FMT"),
          values=c('#BFA366', "#dec14b", "#6E5244")) +
      scale_fill_manual(name="Time_point",
          breaks=c("0","1","2"),
          labels=c("Acclimation","1 week post FMT", "2 weeks post FMT"),
          values=c('#BFA36650', "#dec14b50","#6E524450"))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
    facet_wrap(~ factor(type))+
    stat_compare_means(size=3)+
    theme(legend.position="none")+
    labs(x = "Time_point", y= "Normalized O2 consumption (ml/s/g)")
```

```{r plot_1_1}
respirometry_resp2 %>%
  filter(weight!=5.19)%>%
  ggplot(aes(x = time_point, y = QC_normalized, color=time_point, fill=time_point, alpha=0.2)) +
    geom_boxplot()+
    geom_jitter() +
    scale_color_manual(name="Time_point",
          breaks=c("0","1","2"),
          labels=c("Acclimation","1 week post FMT", "2 weeks post FMT"),
          values=c('#BFA366', "#dec14b", "#6E5244")) +
      scale_fill_manual(name="Time_point",
          breaks=c("0","1","2"),
          labels=c("Acclimation","1 week post FMT", "2 weeks post FMT"),
          values=c('#BFA36650', "#dec14b50","#6E524450"))+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
    facet_wrap(~ factor(type))+
    stat_compare_means(size=3)+
    theme(legend.position="none")+
    labs(x = "Time_point", y= "Normalized O2 consumption (ml/s/g)")+
    geom_signif(comparisons = list(c("0", "1"), c("0", "2"), c("1", "2")),
              map_signif_level = TRUE)
```

# Raw data modelling (LMM)

```{r model}
#Create linear model formula
formula <- formula(QC_normalized ~ time_point*type+(1|individual))

#Fit the linear model
model <- lmer(formula, data = respirometry_resp2)

#Print the model summary
summary(model)
MuMIn::r.squaredGLMM(model)

```


## Raw data modelling (LM) without random effect

```{r model_1}
#Create linear model formula
formula1 <- formula(QC_normalized ~ time_point*type) #QC_normalized=o2 consumption normalized (ml/s)

#Fit the linear model
model1 <- lm(formula1, data = respirometry_resp2)

#Print the model summary
summary(model1)
```

# Data modeling without WC

## LMM

```{r model_2}
#Filter out WC from the dataframe and create a subset
respirometry_resp2_cold<-respirometry_resp2%>%
  filter(type!="WC")%>%
  filter(QC_normalized!=0.000036)

#Create linear model formula
formula4 <- formula(QC_normalized ~ time_point*type+(1|individual))

#Fit the linear model
model4 <- lmer(formula4, data = respirometry_resp2_cold)

#Print the model summary
summary(model4)
MuMIn::r.squaredGLMM(model4)

```

## Linear model without random effect

```{r model_3}
#Create linear model formula
formula5 <- formula(QC_normalized ~ time_point*type)

#Fit the linear model
model5 <- lm(formula5, data = respirometry_resp2_cold)

#Print the model summary
summary(model5)

```
